name = "parkpulse-api"
main = "src/index.js"
compatibility_date = "2026-09-01"

[secrets]
required = ["VAPID_SERVER_PRIVATE_KEY", "THEMEPARKS_API_KEY", "REFRESH_ADMIN_TOKEN"]

[vars]
APP_URL = "https://app.useparkpulse.com/"
APP_ORIGIN = "https://app.useparkpulse.com"
VAPID_SUBJECT = "https://useparkpulse.com/"
VAPID_SERVER_PUBLIC_KEY = "BHtuKXYgGJV5cKKyxBecL9DkMp7l86ehRoF3fkTFp2l1G9HkrGlz3GLVlBuYrGf7FXx3zSJUO7GCb-xIYligQ5w"

[[d1_databases]]
binding = "DB"
database_name = "parkpulse"
database_id = "3ccecfb8-45f9-49f4-a5e7-e90bdf5e9edb"

[triggers]
crons = ["*/5 * * * *"]
